name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: Tag name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          pip install wheel
          python -mvenv venv
          . venv/bin/activate
          python3 setup.py install
          ls -l build/lib/ua_parser
        
      - name: Release
        if: github.event.inputs.tag_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.inputs.tag_name }}
        run: |
          zip -j ua_parser.zip build/lib/ua_parser/*.py
          gh release create "$TAG" --title "$TAG"
          gh release upload "$TAG" ua_parser.zip
          
      - name: Dist
        if: github.event.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone "$GITHUB_REPOSITORY" dist -- -b dist
          cd dist
          cp ../build/lib/ua_parser/*.py .
          git add .
          git commit -m 'Update'
          git push origin dist
          
