name: CI

on:
#   push:
#     branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: Tag name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          python setup.py install

      - uses: actions/checkout@v2
        with:
          ref: dist
          path: dist

      - name: Dist
        run: |
          cd dist
          cp ../build/lib/ua_parser/*.py .

      - name: Release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: dist
          branch: dist
          commit_message: Update
      
      - name: Tag
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist
          gh release create "${{ github.event.inputs.tag_name }}" --target dist
