name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: Tag name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          pip install wheel
          python -mvenv venv
          . venv/bin/activate
          python3 setup.py install
          ls -l build/lib/ua_parser

      - uses: actions/checkout@v2
        with:
          ref: dist
          path: dist

      - name: Dist
        run: |
          cd dist
          cp ../build/lib/ua_parser/*.py .

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: dist
          branch: dist
          commit_message: Update
