name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: Tag name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          python -mvenv venv
          . venv/bin/activate
          python3 setup.py install
          ls -l build/lib/ua_parser
        
      - name: Release
        if: github.event.inputs.tag_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.inputs.tag_name }}
        run: |
          zip ua_parser.zip build/lib/ua_parser/*.py
          gh release create "$TAG" --title "$TAG"
          gh release upload "$TAG" ua_parser.zip
        
