name: CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: Tag name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          python setup.py install
          
          cat << EOF > build/lib/setup.py
          # -*- coding: utf-8 -*-
          from setuptools import setup

          setup(
              name='ua-parser',
              version='0.15.0',
              packages=['ua_parser'],
              url='https://github.com/kaltura/uap-python',
              license='Apache2',
              zip_safe=True
          )
          EOF
          
          cd build/lib
          zip -r $GITHUB_WORKSPACE/ua_parser.zip .
          cat setup.py

      - name: Dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.inputs.tag_name }}
        run: |
          gh release create "$TAG" --title "$TAG"
          gh release upload "$TAG" ua_parser.zip
