name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          python setup.py install
          
      - name: Dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          mv build/lib dist
          cat << EOF > dist/setup.py
          # -*- coding: utf-8 -*-
          from setuptools import setup

          setup(
              name='ua-parser',
              version='$VERSION',
              packages=['ua_parser'],
              url='https://github.com/kaltura/uap-python',
              license='Apache2',
              zip_safe=True
          )
          EOF
          
          pushd dist
          cat << EOF > ua_parser/__init__.py
          VERSION_STR = '$VERSION'
          VERSION = tuple(int(n) for n in VERSION_STR.split('.'))
          EOF
          
          zip -r ../ua_parser.zip .
          cat ua_parser/__init__.py
          cat setup.py
          
          popd
        
          TAG="v$VERSION"
          gh release create "$TAG" --title "$TAG"
          gh release upload "$TAG" ua_parser.zip
          
          
